name: Build & Push multi-base images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Debian 13 image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.deb13
          push: true
          tags: |
            ghcr.io/poweredger710/micro:deb13-1
            ghcr.io/poweredger710/micro:latest-deb13

      - name: Build & push Ubuntu 22 image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.ubuntu22
          push: true
          tags: |
            ghcr.io/poweredger710/micro:ubuntu22-1
            ghcr.io/poweredger710/micro:latest-ubuntu22

      - name: Build & push Ubuntu 24 image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.ubuntu24
          push: true
          tags: |
            ghcr.io/poweredger710/micro:ubuntu24-1
            ghcr.io/poweredger710/micro:latest-ubuntu22
